### PR TITLE
Update panda-client to version 1.4.88

### PR DESCRIPTION
**Pull request by yesw2000**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yesw2000** [comment]
@beckermr

Please help merge this new version of **panda-client**.

Thanks,

**Comment by beckermr** [comment]
You have write access here and do not need me to merge. You need to accept the invite to the conda forge org

**Comment by yesw2000** [comment]
@beckermr ,

Sorry. Where can I see the invite?

**Comment by beckermr** [comment]
check your email. there is a weblink but IDK what it is.

**Pull request merged**
